CREATE TABLE Categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

INSERT INTO categories (name)
VALUES ('ELECTRONICS'),
       ('CLOTHING'),
       ('HOME_AND_LIVING'),
       ('BOOKS'),
       ('GARDEN'),
       ('SPORTS'),
       ('BEAUTY'),
       ('OTHER');