CREATE TABLE Products
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255)   NOT NULL,
    description TEXT,
    price       DECIMAL(10, 2) NOT NULL,
    brand_id    BIGINT,
    category_id BIGINT,
    created_at  TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP      NOT NULL DEFAULT now(),
    FOREIGN KEY (brand_id) REFERENCES Brands (id),
    FOREIGN KEY (category_id) REFERENCES Categories (id)
);