CREATE TABLE Products
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255)   NOT NULL,
    description      TEXT,
    price            NUMERIC(10, 2) NOT NULL,
    compare_at_price NUMERIC(10, 2),
    sku              VARCHAR(100)   NOT NULL UNIQUE,
    category_id      BIGINT         NOT NULL,
    sub_category     VARCHAR(100),
    stock_quantity   INT            NOT NULL DEFAULT 0,
    in_stock         BOOLEAN        NOT NULL DEFAULT TRUE,
    thumbnail_url    VARCHAR(500),
    average_rating   NUMERIC(2, 1)  NOT NULL DEFAULT 0.0,
    review_count     INT            NOT NULL DEFAULT 0,
    active           BOOLEAN        NOT NULL DEFAULT TRUE,
    featured         BOOLEAN        NOT NULL DEFAULT FALSE,
    created_at       TIMESTAMP      NOT NULL DEFAULT NOW(),
    updated_at       TIMESTAMP      NOT NULL DEFAULT NOW(),
    FOREIGN KEY (category_id) REFERENCES Categories (id)
);

CREATE TABLE product_tags
(
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    tag        VARCHAR(100) NOT NULL
);

CREATE TABLE product_images
(
    product_id BIGINT       NOT NULL REFERENCES products (id) ON DELETE CASCADE,
    image_url  VARCHAR(500) NOT NULL
);

CREATE INDEX idx_products_category ON products (category_id);
CREATE INDEX idx_products_featured ON products (featured) WHERE featured = TRUE;
CREATE INDEX idx_products_active ON products (active) WHERE active = TRUE;
CREATE INDEX idx_products_in_stock ON products (in_stock) WHERE in_stock = TRUE;
CREATE INDEX idx_product_tags_product ON product_tags (product_id);